### ISSUE TITLE
TypeError: Cannot read property 'Component' of undefined

### ISSUE THREAD

**Issue by CervantesVive** [dalcib/jest-expo-ts#1]
When running `yarn run jest` I get

```
 FAIL  tests/App.test.tsx
  ● Test suite failed to run

    TypeError: Cannot read property 'Component' of undefined
      
      at Object.<anonymous> (App.tsx:5:34)
      at Object.<anonymous> (tests/App.test.tsx:5:15)

Test Suites: 1 failed, 1 total
```

This is using the template from `create-react-native-app`.

**Comment by dalcib** [comment]
Are you using `import * as React from 'react'` instead of `import React from 'react'` ?

**Comment by CervantesVive** [comment]
Now I am seeing a different problem
```

 FAIL  tests/App.test.tsx
  ● Test suite failed to run

    Cannot find module 'react/lib/ReactCurrentOwner' from 'ReactFiberTreeReflection.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/react-test-renderer/lib/ReactFiberTreeReflection.js:15:25)
```

**Comment by dalcib** [comment]
Try this:
```
import * as React from 'react';
import 'react-native';
import App from '../src/App';

import * as renderer from 'react-test-renderer';

it('renders without crashing', () => {
  const rendered = renderer.create(<App />).toJSON();
  expect(rendered).toBeTruthy();
});
```

**Comment by CervantesVive** [comment]
I still get the same error

```
 FAIL  tests/App.test.tsx
  ● Test suite failed to run

    Cannot find module 'react/lib/ReactCurrentOwner' from 'ReactFiberTreeReflection.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:169:17)
      at Object.<anonymous> (node_modules/react-test-renderer/lib/ReactFiberTreeReflection.js:15:25)
```

**Comment by dalcib** [comment]
@CervantesVive, you can clone this repo to try:
https://github.com/dalcib/expo-ts-exemple

**Comment by CervantesVive** [comment]
Changed several things on the project I am using and now it works:

- For some reason in package.json I had these 
```
    "jest-expo": "~1.0.1",
    "jest-expo-ts": "^0.3.0",
```
- in tsconfig.json I had
```
"module": "es2015",
"jsx": "react-native"
```
I might have either generated them with older tooling or updated them manually based on other github comments/issues.

Once I aligned them with the values in your example project seems tooling is working as expected now.

Thanks again for the help @dalcib !
